#!/usr/bin/env bash

################################################################################
# @ddblock_begin copyright
#
# Copyright (c) 1997-2015
# Maryland DSPCAD Research Group, The University of Maryland at College Park 
#
# Permission is hereby granted, without written agreement and without
# license or royalty fees, to use, copy, modify, and distribute this
# software and its documentation for any purpose, provided that the above
# copyright notice and the following two paragraphs appear in all copies
# of this software.
# 
# IN NO EVENT SHALL THE UNIVERSITY OF MARYLAND BE LIABLE TO ANY PARTY
# FOR DIRECT, INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES
# ARISING OUT OF THE USE OF THIS SOFTWARE AND ITS DOCUMENTATION, EVEN IF
# THE UNIVERSITY OF MARYLAND HAS BEEN ADVISED OF THE POSSIBILITY OF
# SUCH DAMAGE.
# 
# THE UNIVERSITY OF MARYLAND SPECIFICALLY DISCLAIMS ANY WARRANTIES,
# INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE. THE SOFTWARE
# PROVIDED HEREUNDER IS ON AN "AS IS" BASIS, AND THE UNIVERSITY OF
# MARYLAND HAS NO OBLIGATION TO PROVIDE MAINTENANCE, SUPPORT, UPDATES,
# ENHANCEMENTS, OR MODIFICATIONS.
#
# @ddblock_end copyright
################################################################################

# Update copyright notices in selected files

################################################################################
# Some conventions/guidelines about adapting this template for specific
# project directories:
#
# Don't place copyright notices in README.txt files (except for the
# the README.txt file in the package direcortory root).
#
# Use ddputcpr to process individual files. Don't use ddputcpr on 
# directories. Each relevant directory should have its own cprupdate script.
#
# Use ddputcprd to process all files in the current subdirectory that have
# a given extension
#
# Remove code in this script that you don't need instead of commenting it out.
################################################################################

# Usage: cprupdate <no args>

# All Bash scripts.
# ddputcprd ""

# All C source code files.
ddputcprd cpp
ddputcprd cu
ddputcprd h

# Selected text file(s).
# dputcpr configuration-data.txt
